[package]
name = "remodel"
version = "0.6.1"
description = "A tool to read, modify, and write Roblox objects."
authors = ["Lucien Greathouse <me@lpghatguy.com>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/rojo-rbx/remodel"
documentation = "https://github.com/rojo-rbx/remodel"
repository = "https://github.com/rojo-rbx/remodel"
readme = "README.md"

[dependencies]
log = "0.4.8"
rbx_binary = "0.4.1"
rbx_dom_weak = "1.10.0"
rbx_xml = "0.11.2"
rbx_reflection = "3.2.399"
reqwest = "0.9.20"
rlua = "0.17.0"
structopt = "0.3.1"

[target.'cfg(windows)'.dependencies]
winreg = "0.6.2"

[dependencies.env_logger]
version = "0.7.1"
default-features = false
features = ["termcolor", "atty"]